import type { ProductFormatMethodology } from "./types";

export const productFormats: ProductFormatMethodology[] = [
  {
    id: "ebook",
    name: "Ebook",
    structureType: "capitulos",
    idealQuantity: 8,
    positioningLogic:
      "Bom para organizar conhecimento em um material direto, barato de produzir e facil de consumir sozinho.",
    aliases: ["ebook", "e-book", "guia", "pdf", "livro digital"],
    steps: [
      { name: "Introducao", objective: "Apresentar a promessa e preparar o leitor para agir." },
      { name: "Capitulo 1", objective: "Explicar o problema central e por que ele acontece." },
      { name: "Capitulo 2", objective: "Ensinar o primeiro principio ou diagnostico." },
      { name: "Capitulo 3", objective: "Mostrar o metodo principal em passos simples." },
      { name: "Capitulo 4", objective: "Aplicar o metodo em um exemplo pratico." },
      { name: "Conclusao", objective: "Fechar o raciocinio e reforcar a transformacao." },
      { name: "Checklist", objective: "Dar uma lista objetiva para execucao." },
      { name: "Proximos passos", objective: "Orientar o que fazer depois de consumir o material." },
    ],
  },
  {
    id: "recorded_course",
    name: "Curso gravado",
    structureType: "modulos",
    idealQuantity: 7,
    positioningLogic:
      "Bom para ensinar passo a passo com escala, sem depender de agenda individual para cada aluno.",
    aliases: ["curso gravado", "aulas gravadas", "video aulas", "videoaulas"],
    steps: [
      { name: "Boas-vindas", objective: "Alinhar expectativas e mostrar como aproveitar o curso." },
      { name: "Modulo 1", objective: "Diagnosticar o ponto de partida do aluno." },
      { name: "Modulo 2", objective: "Ensinar a base estrategica da transformacao." },
      { name: "Modulo 3", objective: "Executar a primeira parte do metodo." },
      { name: "Modulo 4", objective: "Avancar para a aplicacao pratica." },
      { name: "Modulo 5", objective: "Consolidar o resultado e corrigir erros comuns." },
      { name: "Bonus", objective: "Adicionar um material de apoio que acelere a execucao." },
    ],
  },
  {
    id: "live_course",
    name: "Curso ao vivo",
    structureType: "aulas ao vivo",
    idealQuantity: 5,
    positioningLogic:
      "Bom quando a entrega ganha valor com interacao, prazo definido e acompanhamento durante a execucao.",
    aliases: ["curso ao vivo", "aulas ao vivo", "turma ao vivo"],
    steps: [
      { name: "Aula 1", objective: "Apresentar o mapa e diagnosticar o problema." },
      { name: "Aula 2", objective: "Ensinar a base do metodo." },
      { name: "Aula 3", objective: "Guiar a execucao principal." },
      { name: "Aula 4", objective: "Revisar aplicacoes e ajustar dificuldades." },
      { name: "Aula 5", objective: "Fechar com plano de continuidade." },
    ],
  },
  {
    id: "individual_mentoring",
    name: "Mentoria individual",
    structureType: "encontros individuais",
    idealQuantity: 5,
    positioningLogic:
      "Bom para resolver um problema especifico com alto nivel de personalizacao e ticket maior.",
    aliases: ["mentoria individual", "acompanhamento individual", "1:1", "one to one"],
    steps: [
      { name: "Encontro 1", objective: "Diagnostico profundo da situacao atual." },
      { name: "Encontro 2", objective: "Plano de acao personalizado." },
      { name: "Encontro 3", objective: "Execucao guiada da primeira etapa." },
      { name: "Encontro 4", objective: "Correcoes, ajustes e destravamento." },
      { name: "Encontro 5", objective: "Escala, continuidade ou autonomia." },
    ],
  },
  {
    id: "group_mentoring",
    name: "Mentoria em grupo",
    structureType: "encontros em grupo",
    idealQuantity: 6,
    positioningLogic:
      "Bom para entregar acompanhamento com mais escala, mantendo troca, comunidade e senso de compromisso.",
    aliases: ["mentoria em grupo", "grupo de mentoria", "acompanhamento em grupo"],
    steps: [
      { name: "Encontro 1", objective: "Diagnostico coletivo e alinhamento de metas." },
      { name: "Encontro 2", objective: "Plano de acao comum com ajustes por perfil." },
      { name: "Encontro 3", objective: "Execucao da primeira entrega." },
      { name: "Encontro 4", objective: "Analise de casos e correcoes." },
      { name: "Encontro 5", objective: "Aprofundamento e melhoria do resultado." },
      { name: "Encontro 6", objective: "Plano de continuidade e proximos passos." },
    ],
  },
  {
    id: "workshop",
    name: "Workshop",
    structureType: "agenda",
    idealQuantity: 5,
    positioningLogic:
      "Bom para entregar uma conquista especifica em poucas horas e vender uma proxima etapa depois.",
    aliases: ["workshop", "oficina", "aula pratica", "intensivo"],
    steps: [
      { name: "Abertura", objective: "Apresentar o objetivo e o resultado esperado." },
      { name: "Diagnostico rapido", objective: "Fazer o participante entender seu ponto de partida." },
      { name: "Metodo principal", objective: "Ensinar o passo a passo central." },
      { name: "Aplicacao ao vivo", objective: "Guiar uma execucao pratica durante o encontro." },
      { name: "Fechamento", objective: "Mostrar proximos passos e oferta de continuidade." },
    ],
  },
  {
    id: "community",
    name: "Comunidade",
    structureType: "calendario",
    idealQuantity: 6,
    positioningLogic:
      "Bom para temas em que a pessoa precisa de recorrencia, troca e acompanhamento continuo.",
    aliases: ["comunidade", "comunidade paga", "clube", "assinatura"],
    steps: [
      { name: "Onboarding", objective: "Receber o membro e orientar o primeiro resultado." },
      { name: "Encontro semanal", objective: "Manter ritmo de aprendizado e execucao." },
      { name: "Plantao de duvidas", objective: "Remover travas especificas dos membros." },
      { name: "Desafio mensal", objective: "Criar uma meta pratica com prazo." },
      { name: "Biblioteca", objective: "Organizar materiais, aulas e templates." },
      { name: "Ritual de progresso", objective: "Medir evolucao e estimular permanencia." },
    ],
  },
  {
    id: "consulting",
    name: "Consultoria",
    structureType: "fases de consultoria",
    idealQuantity: 5,
    positioningLogic:
      "Bom quando o cliente quer orientacao especializada para tomar decisoes e implementar com seguranca.",
    aliases: ["consultoria", "consultoria estrategica", "diagnostico"],
    steps: [
      { name: "Diagnostico", objective: "Entender contexto, problema e restricoes." },
      { name: "Analise", objective: "Organizar achados e identificar prioridades." },
      { name: "Plano de acao", objective: "Definir recomendacoes e ordem de execucao." },
      { name: "Implementacao assistida", objective: "Acompanhar as primeiras aplicacoes." },
      { name: "Revisao", objective: "Medir resultado e ajustar proximas decisoes." },
    ],
  },
  {
    id: "template",
    name: "Template ou kit pronto",
    structureType: "pecas do kit",
    idealQuantity: 6,
    positioningLogic:
      "Bom quando o publico quer ganhar tempo usando modelos prontos em vez de aprender tudo do zero.",
    aliases: ["template", "kit", "kit pronto", "modelos prontos", "templates"],
    steps: [
      { name: "Guia de uso", objective: "Explicar como usar o kit sem se perder." },
      { name: "Template principal", objective: "Entregar o modelo que resolve a maior dor." },
      { name: "Template de apoio", objective: "Cobrir uma etapa complementar da execucao." },
      { name: "Exemplo preenchido", objective: "Mostrar como fica uma aplicacao correta." },
      { name: "Checklist de revisao", objective: "Evitar erros comuns antes de publicar ou usar." },
      { name: "Proximos passos", objective: "Orientar como repetir o processo." },
    ],
  },
  {
    id: "checklist",
    name: "Checklist",
    structureType: "etapas de verificacao",
    idealQuantity: 6,
    positioningLogic:
      "Bom para transformar um processo confuso em uma sequencia clara de verificacao e acao.",
    aliases: ["checklist", "lista de checagem"],
    steps: [
      { name: "Preparacao", objective: "Separar o que precisa existir antes de comecar." },
      { name: "Diagnostico", objective: "Identificar o que esta faltando ou errado." },
      { name: "Execucao", objective: "Marcar as acoes essenciais em ordem." },
      { name: "Revisao", objective: "Conferir qualidade antes de finalizar." },
      { name: "Publicacao ou entrega", objective: "Garantir que o resultado chegue ao destino certo." },
      { name: "Acompanhamento", objective: "Orientar o que medir depois." },
    ],
  },
  {
    id: "spreadsheet",
    name: "Planilha pronta",
    structureType: "abas",
    idealQuantity: 5,
    positioningLogic:
      "Bom quando o problema envolve calculo, acompanhamento, controle ou comparacao recorrente.",
    aliases: ["planilha", "planilha pronta", "controle", "dashboard em planilha"],
    steps: [
      { name: "Aba 1", objective: "Cadastro ou entrada dos dados principais." },
      { name: "Aba 2", objective: "Organizacao das informacoes por categoria." },
      { name: "Aba 3", objective: "Calculos e indicadores essenciais." },
      { name: "Aba 4", objective: "Relatorios ou visualizacao de resultado." },
      { name: "Aba 5", objective: "Plano de acao com base nos dados." },
    ],
  },
  {
    id: "challenge",
    name: "Desafio",
    structureType: "dias",
    idealQuantity: 5,
    positioningLogic:
      "Bom para gerar progresso rapido, compromisso diario e sensacao clara de transformacao.",
    aliases: ["desafio", "desafio de 5 dias", "jornada curta"],
    steps: [
      { name: "Dia 1", objective: "Diagnosticar e definir o ponto de partida." },
      { name: "Dia 2", objective: "Organizar a base da solucao." },
      { name: "Dia 3", objective: "Executar a primeira entrega concreta." },
      { name: "Dia 4", objective: "Ajustar, melhorar e completar o processo." },
      { name: "Dia 5", objective: "Finalizar com checklist e proximos passos." },
    ],
  },
  {
    id: "gpt_agent",
    name: "Agente GPT",
    structureType: "funcionalidades",
    idealQuantity: 6,
    positioningLogic:
      "Bom quando o conhecimento pode virar assistente interativo, repetivel e util para decisoes ou producao.",
    aliases: ["agente gpt", "gpt", "assistente de ia", "agente de ia"],
    steps: [
      { name: "Funcionalidade 1", objective: "Resolver a primeira tarefa essencial do usuario." },
      { name: "Funcionalidade 2", objective: "Apoiar uma decisao ou diagnostico recorrente." },
      { name: "Biblioteca", objective: "Guardar referencias, exemplos e criterios." },
      { name: "Templates", objective: "Oferecer respostas ou estruturas prontas." },
      { name: "Prompt inicial", objective: "Guiar o usuario para usar o agente corretamente." },
      { name: "Exemplos", objective: "Mostrar situacoes reais de uso." },
    ],
  },
  {
    id: "mini_saas",
    name: "Mini SaaS ou ferramenta web",
    structureType: "funcionalidades",
    idealQuantity: 5,
    positioningLogic:
      "Bom quando a dor se repete e pode ser resolvida com uma ferramenta simples, sem depender de conteudo longo.",
    aliases: ["mini saas", "mini-saas", "ferramenta web", "sistema", "software"],
    steps: [
      { name: "Dashboard", objective: "Dar visao rapida do estado atual e proximas acoes." },
      { name: "Cadastro", objective: "Coletar dados essenciais para personalizar a entrega." },
      { name: "Relatorios", objective: "Mostrar resultados, alertas ou comparacoes." },
      { name: "Automacoes", objective: "Reduzir trabalho manual recorrente." },
      { name: "Configuracao", objective: "Permitir ajustes simples ao contexto do usuario." },
    ],
  },
  {
    id: "service",
    name: "Servico feito para o cliente",
    structureType: "fases de entrega",
    idealQuantity: 5,
    positioningLogic:
      "Bom quando o publico quer o resultado pronto e nao quer aprender ou executar sozinho.",
    aliases: ["servico", "feito para o cliente", "done for you", "feito por voce"],
    steps: [
      { name: "Briefing", objective: "Coletar informacoes e alinhar expectativas." },
      { name: "Diagnostico", objective: "Identificar o melhor caminho de execucao." },
      { name: "Producao", objective: "Criar a entrega principal para o cliente." },
      { name: "Revisao", objective: "Ajustar detalhes antes da entrega final." },
      { name: "Entrega", objective: "Finalizar, orientar uso e indicar proximos passos." },
    ],
  },
];
